/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBingimgRouteImport } from './routes/api/bingimg'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiSuggestRouteImport } from './routes/api/suggest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBingimgRoute = ApiBingimgRouteImport.update({
  id: '/api/bingimg',
  path: '/api/bingimg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestRoute = ApiSuggestRouteImport.update({
  id: '/api/suggest',
  path: '/api/suggest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/bingimg': typeof ApiBingimgRoute
  '/api/chat': typeof ApiChatRoute
  '/api/suggest': typeof ApiSuggestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/bingimg': typeof ApiBingimgRoute
  '/api/chat': typeof ApiChatRoute
  '/api/suggest': typeof ApiSuggestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/bingimg': typeof ApiBingimgRoute
  '/api/chat': typeof ApiChatRoute
  '/api/suggest': typeof ApiSuggestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/bingimg' | '/api/chat' | '/api/suggest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/bingimg' | '/api/chat' | '/api/suggest'
  id: '__root__' | '/' | '/api/bingimg' | '/api/chat' | '/api/suggest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBingimgRoute: typeof ApiBingimgRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSuggestRoute: typeof ApiSuggestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bingimg': {
      id: '/api/bingimg'
      path: '/api/bingimg'
      fullPath: '/api/bingimg'
      preLoaderRoute: typeof ApiBingimgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggest': {
      id: '/api/suggest'
      path: '/api/suggest'
      fullPath: '/api/suggest'
      preLoaderRoute: typeof ApiSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBingimgRoute: ApiBingimgRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSuggestRoute: ApiSuggestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
