/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBingimgRouteImport } from './routes/api/bingimg'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiGimgRouteImport } from './routes/api/gimg'
import { Route as ApiLyricsRouteImport } from './routes/api/lyrics'
import { Route as ApiMusicRouteImport } from './routes/api/music'
import { Route as ApiSuggestRouteImport } from './routes/api/suggest'
import { Route as ApiWeatherRouteImport } from './routes/api/weather'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBingimgRoute = ApiBingimgRouteImport.update({
  id: '/api/bingimg',
  path: '/api/bingimg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGimgRoute = ApiGimgRouteImport.update({
  id: '/api/gimg',
  path: '/api/gimg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLyricsRoute = ApiLyricsRouteImport.update({
  id: '/api/lyrics',
  path: '/api/lyrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMusicRoute = ApiMusicRouteImport.update({
  id: '/api/music',
  path: '/api/music',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestRoute = ApiSuggestRouteImport.update({
  id: '/api/suggest',
  path: '/api/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherRoute = ApiWeatherRouteImport.update({
  id: '/api/weather',
  path: '/api/weather',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/bingimg': typeof ApiBingimgRoute
  '/api/chat': typeof ApiChatRoute
  '/api/gimg': typeof ApiGimgRoute
  '/api/lyrics': typeof ApiLyricsRoute
  '/api/music': typeof ApiMusicRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/api/weather': typeof ApiWeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/bingimg': typeof ApiBingimgRoute
  '/api/chat': typeof ApiChatRoute
  '/api/gimg': typeof ApiGimgRoute
  '/api/lyrics': typeof ApiLyricsRoute
  '/api/music': typeof ApiMusicRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/api/weather': typeof ApiWeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/bingimg': typeof ApiBingimgRoute
  '/api/chat': typeof ApiChatRoute
  '/api/gimg': typeof ApiGimgRoute
  '/api/lyrics': typeof ApiLyricsRoute
  '/api/music': typeof ApiMusicRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/api/weather': typeof ApiWeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/bingimg'
    | '/api/chat'
    | '/api/gimg'
    | '/api/lyrics'
    | '/api/music'
    | '/api/suggest'
    | '/api/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/bingimg'
    | '/api/chat'
    | '/api/gimg'
    | '/api/lyrics'
    | '/api/music'
    | '/api/suggest'
    | '/api/weather'
  id:
    | '__root__'
    | '/'
    | '/api/bingimg'
    | '/api/chat'
    | '/api/gimg'
    | '/api/lyrics'
    | '/api/music'
    | '/api/suggest'
    | '/api/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBingimgRoute: typeof ApiBingimgRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGimgRoute: typeof ApiGimgRoute
  ApiLyricsRoute: typeof ApiLyricsRoute
  ApiMusicRoute: typeof ApiMusicRoute
  ApiSuggestRoute: typeof ApiSuggestRoute
  ApiWeatherRoute: typeof ApiWeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bingimg': {
      id: '/api/bingimg'
      path: '/api/bingimg'
      fullPath: '/api/bingimg'
      preLoaderRoute: typeof ApiBingimgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gimg': {
      id: '/api/gimg'
      path: '/api/gimg'
      fullPath: '/api/gimg'
      preLoaderRoute: typeof ApiGimgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lyrics': {
      id: '/api/lyrics'
      path: '/api/lyrics'
      fullPath: '/api/lyrics'
      preLoaderRoute: typeof ApiLyricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/music': {
      id: '/api/music'
      path: '/api/music'
      fullPath: '/api/music'
      preLoaderRoute: typeof ApiMusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggest': {
      id: '/api/suggest'
      path: '/api/suggest'
      fullPath: '/api/suggest'
      preLoaderRoute: typeof ApiSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather': {
      id: '/api/weather'
      path: '/api/weather'
      fullPath: '/api/weather'
      preLoaderRoute: typeof ApiWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBingimgRoute: ApiBingimgRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGimgRoute: ApiGimgRoute,
  ApiLyricsRoute: ApiLyricsRoute,
  ApiMusicRoute: ApiMusicRoute,
  ApiSuggestRoute: ApiSuggestRoute,
  ApiWeatherRoute: ApiWeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
